### ISSUE TITLE
Roadmap for the project

### ISSUE THREAD

**Issue by Yasirunet** [Yasirunet/OpenIntra#1]
The project consists of the following modules. We hope to go through the following module by module as listed below.

- [ ] Employee contact registry.
- [ ] Company Events/Meetings/working Calendar
- [ ] Meeting room Booking system & meeting minutes
- [ ] Management Availability schedule
- [ ] Document Management system with permissions
- [ ] Visitor Pass Approval system
